name: Create Alpha Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet'
        default: 'World'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          node-version: 14
          npm-dist-tag: alpha
          default-branch: ${{ env.branch_name }}
