name: Release alpha version

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        type: string
        required: false
        description: 'Manually version of package, e.g. 3.0.0-alpha.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash
      - name: Bump and commit version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ github.event.inputs.packageVersion }} -i prerelease --preid=alpha
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
      - name: Publish version
        run: npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
        shell: bash
