name: Release Alpha-1

on:
  push:
    branches: [alpha/**]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash
      - uses: codex-team/action-nodejs-package-info@v1
        id: package
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ steps.package.outputs.name }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false}]'
          bump-minor-pre-major: true
          prerelease: true
      - run: npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
