name: Release version 1.x.x.

on:
  push:
    branches: [yuberdysheva/alpha-released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          node-version: 18
          npm-dist-tag: untagged
          default-branch: yuberdysheva/alpha-released
