name: Release alpha version

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        type: string
        required: false
        description: 'Manually version of package, e.g. 3.0.0-alpha.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash
      - name: Bump and commit version
        shell: bash
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
        run: 'npm version ${{ github.event.inputs.packageVersion }} -i prerelease --preid=alpha && git push'
      - name: Publish version
        run: npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
        shell: bash
