name: Release alpha version

on:
  workflow_dispatch:
    inputs:
      manualPackageVersion:
        type: string
        required: false
        description: 'Manually version of package, e.g. 3.0.0-alpha.0'
      prereleaseType:
        type: choice
        description: 'You can chose which one prerelease do you want (prepatch | preminor). Default value is prepatch. You have to set it on time. Do not set up anything here if you want to increase only version after `alpha` '
        required: false
        options:
          - 'prepatch'
          - 'preminor'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        shell: bash
      - run: npm test
        shell: bash
      - name: Bump and commit version
        if:
        run: |
          git config --local user.email "111915794+gravity-ui-bot@users.noreply.github.com"
          git config --local user.name "gravity-ui-bot"

          echo ${{ github.event.inputs.manualPackageVersion }}
          echo ${{ github.event.inputs.prereleaseType }}

          if [ "${{ github.event.inputs.manualPackageVersion }}" == "" ]; then
            if [ "${{ github.event.inputs.prereleaseType }}" == "" ]; then
              npm version ${{ github.event.inputs.prereleaseType }} --preid=alpha
            else
              npm version 
          else
            npm version ${{ github.event.inputs.manualPackageVersion }}
          fi

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
        id: extract_branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
      - name: Publish version
        run: npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
        shell: bash
